# Force Ubuntu 16.04 "Xenial" to get newer GCC, binutils etc.
dist: xenial
language: c

env:
  global:
    - CFLAGS="--coverage -O2 -g"
    - LDFLAGS="--coverage"

compiler:
  - clang
  - gcc

# temporary hack with sed until we will have a proper configure script
script:
  - ./autogen.sh && ./configure
  - make -j2 V=1
  - cd tst && ./run_all.sh

after_script:
  - gcov functions/*/*.c
  - bash <(curl -s https://codecov.io/bash)
