# Force Ubuntu 16.04 "Xenial" to get newer GCC, binutils etc.
dist: xenial
language: c

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
    - os: osx
    #- os: windows

# temporary hack with sed until we will have a proper configure script
script:
  - set -e
  - perl -pi -e "s|TOPDIR=/path/to/the/directory/containing/this/makefile|TOPDIR=$PWD|g" Makefile
  - perl -pi -e 's|CFLAGS = -g -Wall -DDIAG1|CFLAGS = --coverage -g -Wall -DDIAG1|g' Makefile
  - make
  - cd bin; ln -s `ls -d */` carat
  - cd ../tst; ./run_all.sh

after_script:
  - gcov functions/*/*.c
  - bash <(curl -s https://codecov.io/bash)
