# Force Ubuntu 16.04 "Xenial" to get newer GCC, binutils etc.
dist: xenial
language: c

# temporary measure until we will have a proper configure script

compiler:
  - clang
  - gcc

script:
  - sed -i 's|TOPCARATDIR=|TOPDIR=/home/travis/build/lbfm-rwth/carat|g' Makefile
  - make
