name: Carat
version: "1.1"
license: "GPL v@.0"
date: 2019-11-10
description: |
    Crystallographic AlgoRithms And Tables

authors:
    - name: Jürgen Opgenorth
      url: 
    - name: Tilman Schulz
      url: 
    - name: Wilhelm Plesken
      url: https://www.mathb.rwth-aachen.de/cms/MATHB/Der-Lehrstuhl/Team/Professorinnen-und-Professoren/~rnmq/Univ-Prof-i-R-Dr-rer-nat-Wilhelm-Pl/lidx/1/

maintainers:
    - name: Dominik Berhardt
      url: https://www.mathb.rwth-aachen.de/cms/MATHB/Der-Lehrstuhl/Team/Wissenschaftliche-Beschaeftigte/~rnsg/Dominik-Bernhardt/lidx/1/

contributors:
    - name: Dominik Bernhardt
      url: https://www.mathb.rwth-aachen.de/cms/MATHB/Der-Lehrstuhl/Team/Wissenschaftliche-Beschaeftigte/~rnsg/Dominik-Bernhardt/lidx/1/
    - name: Franz Gähler
      url: https://www.math.uni-bielefeld.de/~gaehler/
    - name: Max Horn
      url: https://www.quendi.de/math


needed-pkgs:
    - name: "A C compiler, for example gcc"
      version: ""
      url: "https://gcc.gnu.org"

www: https://github.com/lbfm-rwth/carat/
readme: README.md
packageinfo: https://github.com/lbfm-rwth/carat/PackageInfo.g
github: https://github.com/lbfm-rwth/Carat

downloads:
    - name: .tar.gz
      url: https://github.com/lbfm-rwth/Carat/releases/download/v1.1/Carat-1.1.tar.gz
    - name: .tar.bz2
      url: https://github.com/lbfm-rwth/Carat/releases/download/v1.1/Carat-1.1.tar.bz2

abstract: |
    Carat is a computer package which handles enumeration, construction,
    recognition and comparison problems for crystallographic groups up to dimension 6.
    The name CARAT itself is anacronym for Crystallographic AlgoRithms And Tables.

status: other
doc-html: doc/index.html
doc-pdf: doc/manual.pdf
keywords: |
    GitHub Pages, CARAT.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>OPS19</span>]   <b class='BibAuthor'>Opgenorth, J., Plesken, W. and Schulz, T.</b>,
     <i class='BibTitle'>Carat, Crystallographic AlgoRithms And Tables,
             Version 2.0</i>
     (<span class='BibYear'>2019</span>)<br />
    <span class='BibHowpublished'><a href="https://github.com/lbfm-rwth/carat/">https://github.com/lbfm-rwth/carat/</a></span>.
    </p>
    

bibtex: |
    @misc{ Carat1.1,
      author =           {Opgenorth, J., Plesken, W. and Schulz, T.},
      title =            {{Carat}, Crystallographic AlgoRithms And Tables, {V}ersion 1.1},
      month =            {Nov},
      year =             {2019},
      howpublished =     {\href {https://github.com/lbfm-rwth/carat/} {\texttt{https://lbfm-rwth.github.io/}\discretionary {}{}{}\texttt{Carat/}}},
      keywords =         {GitHub Pages; CARAT},
      printedkey =       {OPS19}
    }

