#include"typedef.h"
#include"matrix.h"
#include"polyeder.h"
#include"sort.h"
#include"presentation.h"
#include"getput.h"

/****************************************************************************
@
@----------------------------------------------------------------------------
@----------------------------------------------------------------------------
@ FILE: T_polyeder.c
@----------------------------------------------------------------------------
@----------------------------------------------------------------------------
@
*****************************************************************************/

/**************************************************************************\
@--------------------------------------------------------------------------
@
@polyeder_TYP *T_polyeder(Vec,Mat,Form)
@matrix_TYP *Vec;
@matrix_TYP *Mat;
@matrix_TYP *Form;
@
@calculates the Dirichlet Domain of the column vector Vec under the 
@lattice generated by the rows of Mat using the quadratic form given in Form.
@
@--------------------------------------------------------------------------
\**************************************************************************/

polyeder_TYP *T_polyeder(Vec,Mat,Form)
matrix_TYP *Vec, *Mat, *Form;
{
  matrix_TYP  *otto;
  matrix_TYP  *vvec;
  int anz;
  int i,j;
  wall_TYP **w;
  polyeder_TYP *P;
  
  otto = neukandidat_vectors(Mat,Form);
  
  vvec = copy_mat(Vec);
  real_mat(vvec,vvec->rows-1,vvec->cols);
  w = T_ungleich_wand(vvec,otto,Form,&anz);
  free_mat(vvec); vvec = NULL; /*included 4.3. anne*/
  free_mat(otto); otto = NULL; /*included 4.3. anne*/
  P = first_polyeder(w, anz);
  
  for(i=0;i<anz;i++){
    j =  refine_polyeder(P, w[i]);
  }
  
  for(i=0;i<anz;i++)
    free_wall(&w[i]);
  free(w);
  
  return(P);
}

